# This file will be joined with docker-compose.app.yml from dcape
# See https://github.com/dopos/dcape

services:
  # This service will extend code from dcape
  app:
    environment:
      # See https://www.meilisearch.com/docs/learn/configuration/instance_options
      - MEILI_ENV=production
      - MEILI_MASTER_KEY
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ${APP_ROOT}/db:/meili_data
